version: '2'

services:
  db:
      image: postgres
      # environment:
      #   - POSTGRES_DB=postgres
      #   - POSTGRES_USER=postgres
      #   - POSTGRES_PASSWORD=postgres
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=ss1481  
      - POSTGRES_PASSWORD=2108  
      volumes:
            - data-volume:/var/lib/postgresql/data
      

  web-init:
      build: ./web-app
      user: root
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
        
      depends_on:
        - db
      

  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
        
      expose:
        - "8000"
      depends_on:
        - web-init
      

  backend:
      build: ./backend
      volumes:
        - "./backend:/backend"
      tty: true
      depends_on:
        - db
      ports:
        - "8090:8090"
      command: bash -c "python3 server.py"
      network_mode: "host"
      

  nginx:
      image: nginx:latest
      ports:
        - "8000:8000"
      volumes:
        - ./nginx/config:/etc/nginx/conf.d
      depends_on:
        - web
      

volumes:
   data-volume:
