version: '2'

services:
  db:
      image: postgres
      # environment:
      #   - POSTGRES_DB=postgres
      #   - POSTGRES_USER=postgres
      #   - POSTGRES_PASSWORD=postgres
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=ss1481  
      - POSTGRES_PASSWORD=2108  
      volumes:
            - data-volume:/var/lib/postgresql/data
      

      

  web:
      build: ./web-app
      image: erss-project-xh135-ss1481_web:latest  
      user: root
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
        
      expose:
        - "8000"
      depends_on:
        - db

      

  backend:
      build: ./backend
      volumes:
        - "./backend:/backend"
      tty: true
      depends_on:
        - db
      ports:
        - "34567:34567"
        - "45678:45678"
      command: bash -c "python3 server.py"

      

  nginx:
      image: nginx:latest
      ports:
        - "8000:8000"
      volumes:
        - ./nginx/config:/etc/nginx/conf.d
      depends_on:
        - web
      

volumes:
   data-volume: {}
