# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web_backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='web_backend.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11web_backend.proto\"\'\n\x04Wbuy\x12\x0f\n\x07orderid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"<\n\x08Waskmore\x12\x11\n\tproductid\x18\x01 \x02(\x03\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\";\n\tWCommands\x12\x12\n\x03\x62uy\x18\x01 \x03(\x0b\x32\x05.Wbuy\x12\x1a\n\x07\x61skmore\x18\x02 \x03(\x0b\x32\t.Waskmore\"\x19\n\tBResponse\x12\x0c\n\x04\x61\x63ks\x18\x01 \x03(\x03')
)




_WBUY = _descriptor.Descriptor(
  name='Wbuy',
  full_name='Wbuy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderid', full_name='Wbuy.orderid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Wbuy.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=60,
)


_WASKMORE = _descriptor.Descriptor(
  name='Waskmore',
  full_name='Waskmore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productid', full_name='Waskmore.productid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='Waskmore.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Waskmore.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=122,
)


_WCOMMANDS = _descriptor.Descriptor(
  name='WCommands',
  full_name='WCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy', full_name='WCommands.buy', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='askmore', full_name='WCommands.askmore', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=183,
)


_BRESPONSE = _descriptor.Descriptor(
  name='BResponse',
  full_name='BResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acks', full_name='BResponse.acks', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=210,
)

_WCOMMANDS.fields_by_name['buy'].message_type = _WBUY
_WCOMMANDS.fields_by_name['askmore'].message_type = _WASKMORE
DESCRIPTOR.message_types_by_name['Wbuy'] = _WBUY
DESCRIPTOR.message_types_by_name['Waskmore'] = _WASKMORE
DESCRIPTOR.message_types_by_name['WCommands'] = _WCOMMANDS
DESCRIPTOR.message_types_by_name['BResponse'] = _BRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wbuy = _reflection.GeneratedProtocolMessageType('Wbuy', (_message.Message,), dict(
  DESCRIPTOR = _WBUY,
  __module__ = 'web_backend_pb2'
  # @@protoc_insertion_point(class_scope:Wbuy)
  ))
_sym_db.RegisterMessage(Wbuy)

Waskmore = _reflection.GeneratedProtocolMessageType('Waskmore', (_message.Message,), dict(
  DESCRIPTOR = _WASKMORE,
  __module__ = 'web_backend_pb2'
  # @@protoc_insertion_point(class_scope:Waskmore)
  ))
_sym_db.RegisterMessage(Waskmore)

WCommands = _reflection.GeneratedProtocolMessageType('WCommands', (_message.Message,), dict(
  DESCRIPTOR = _WCOMMANDS,
  __module__ = 'web_backend_pb2'
  # @@protoc_insertion_point(class_scope:WCommands)
  ))
_sym_db.RegisterMessage(WCommands)

BResponse = _reflection.GeneratedProtocolMessageType('BResponse', (_message.Message,), dict(
  DESCRIPTOR = _BRESPONSE,
  __module__ = 'web_backend_pb2'
  # @@protoc_insertion_point(class_scope:BResponse)
  ))
_sym_db.RegisterMessage(BResponse)


# @@protoc_insertion_point(module_scope)
