# Generated by Django 4.2.9 on 2024-04-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
