# Generated by Django 4.2.9 on 2024-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_orderitem_order_orderitem_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='des_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='des_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='ups_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='des_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='des_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='upsUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
