# Generated by Django 4.2.9 on 2024-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cartorder_des_x_cartorder_des_y_cartorder_ups_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upsUserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('error', 'Error'), ('packing', 'Packing'), ('packed', 'Packed'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
